import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Full"
dynamic_padding = false
opacity = 0.95
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"
